server:
  port: 8761

spring:
  application:
    name: discovery-server
  security:
    basic:
      enabled: false
  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 30000
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 90000

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG